
package notitions;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Notes", targetNamespace = "http://notews/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Notes {


    /**
     * 
     * @param text
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNote", targetNamespace = "http://notews/", className = "notitions.AddNote")
    @ResponseWrapper(localName = "addNoteResponse", targetNamespace = "http://notews/", className = "notitions.AddNoteResponse")
    @Action(input = "http://notews/Notes/addNoteRequest", output = "http://notews/Notes/addNoteResponse")
    public boolean addNote(
        @WebParam(name = "text", targetNamespace = "")
        String text);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeNote", targetNamespace = "http://notews/", className = "notitions.RemoveNote")
    @ResponseWrapper(localName = "removeNoteResponse", targetNamespace = "http://notews/", className = "notitions.RemoveNoteResponse")
    @Action(input = "http://notews/Notes/removeNoteRequest", output = "http://notews/Notes/removeNoteResponse")
    public boolean removeNote(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<notitions.Note>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNotes", targetNamespace = "http://notews/", className = "notitions.GetNotes")
    @ResponseWrapper(localName = "getNotesResponse", targetNamespace = "http://notews/", className = "notitions.GetNotesResponse")
    @Action(input = "http://notews/Notes/getNotesRequest", output = "http://notews/Notes/getNotesResponse")
    public List<Note> getNotes();

}
