/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspCServletContext/1.0
 * Generated at: 2017-05-22 10:44:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class Week2Opdracht2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n<!doctype html public \\\"-//w3c//dtd html 4.0 Transitional//EN\\\">\r\n<html>\r\n <head>\r\n <title>\r\n Opdracht 2 van Week 2\r\n </title>\r\n </head>\r\n <body>\r\n <h1>\r\n Hallo dit is de servlet van Opdracht 2 van Week 2\r\n <br>\r\n Dit is de LaatsteAanroep servlet omgebouwd tot JSP pagina.\r\n </h1>\r\n \r\n ");

       // Return the existing session if there is one. Create a new session otherwise.
      HttpSession sessie = request.getSession();
      Integer accessCount;
      synchronized(sessie) {
         accessCount = (Integer)sessie.getAttribute("accessCount");
         if (accessCount == null) {
            accessCount = 0;   // autobox int to Integer
         } else {
            accessCount = new Integer(accessCount + 1);
         }
         sessie.setAttribute("accessCount", accessCount);
      }
 
 
      out.write("\r\n \r\n <h2>You have access this site ");
      out.print( accessCount);
      out.write("  times in this session.</h2>\r\n <p>Session ID is ");
      out.print( sessie.getId() );
      out.write("</p>\r\n <p>Session creation time is  ");
      out.print( new Date(sessie.getCreationTime()) );
      out.write(" </p>\r\n <p>Session last access time is  ");
      out.print( new Date(sessie.getLastAccessedTime()) );
      out.write(" </p>\r\n <p>Session max inactive interval  ");
      out.print( new Date(sessie.getMaxInactiveInterval()) );
      out.write(" </p>\r\n \r\n <p><a  href='");
      out.print(request.getRequestURI());
      out.write("'>Refresh</a>\r\n <p><a  href='");
      out.print(response.encodeURL(request.getRequestURI()));
      out.write("'>Refresh with  URL rewriting</a>\r\n\t\t\t   \r\n </body>\r\n</html>\r");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
